/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_imageblurring_MainActivity */

#ifndef _Included_Java_com_xya_JniMethod_ImageBlur
#define _Included_Java_com_xya_JniMethod_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qiujuer_imageblurring_MainActivity
 * Method:    blurBitMap
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_xya_JniMethod_ImageBlur_blurBitMap
  (JNIEnv *, jclass, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
